"""empty message

Revision ID: 325cba7830f8
Revises: 
Create Date: 2022-04-23 11:07:59.780554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325cba7830f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temp_cart_user_id_fkey', 'temp_cart', type_='foreignkey')
    op.drop_constraint('temp_cart_product_id_fkey', 'temp_cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('temp_cart_product_id_fkey', 'temp_cart', 'product', ['product_id'], ['id'])
    op.create_foreign_key('temp_cart_user_id_fkey', 'temp_cart', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
