"""empty message

Revision ID: 4b9a1f78e97c
Revises: 5fdc37d16d7d
Create Date: 2022-04-25 13:51:39.805008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9a1f78e97c'
down_revision = '5fdc37d16d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'amount')
    # ### end Alembic commands ###
